# Generated by Django 4.1.1 on 2022-09-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disney',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='disney',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hbo',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hbo',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
