# Generated by Django 4.1.1 on 2022-10-12 00:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSeries', '0002_alter_disney_qualification_alter_hbo_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disney',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hbo',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='prime',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
