from django.urls import path
from AppSeries.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name='home'),
    path('recommendingtv/sobrenosotros', sobrenosotros, name='sobrenosotros'),
    path('recommendingtv/netflix/', netflix, name='netflix'),
    path('recommendingtv/primevideo/', primevideo, name='primevideo'),
    path('recommendingtv/hbomax/', hbomax, name='hbomax'),
    path('recommendingtv/disneyplus/', disneyplus, name='disneyplus'),
    path('recommendingtv/detallenetflix/<id>', detallenetflix, name='detallenetflix'),
    path('recommendingtv/detalleprime/<id>', detalleprime, name='detalleprime'),
    path('recommendingtv/detallehbo/<id>', detallehbo, name='detallehbo'),
    path('recommendingtv/detalledisney/<id>', detalledisney, name='detalledisney'),
    path('recommendingtv/netflixform', netflixform, name='netflixform'),
    path('recommendingtv/primeform', primeform, name='primeform'),
    path('recommendingtv/hboform', hboform, name='hboform'),
    path('recommendingtv/disneyform', disneyform, name='disneyform'),
    path('recommendingtv/listanetflix', listanetflix, name='listanetflix'),
    path('recommendingtv/listaprime', listaprime, name='listaprime'),
    path('recommendingtv/listahbo', listahbo, name='listahbo'),
    path('recommendingtv/listadisney', listadisney, name='listadisney'),
    path('recommendingtv/editarserienetflix/<id>', editarserienetflix, name='editarserienetflix'),
    path('recommendingtv/editarserieprime/<id>', editarserieprime, name='editarserieprime'),
    path('recommendingtv/editarseriehbo/<id>', editarseriehbo, name='editarseriehbo'),
    path('recommendingtv/editarseriedisney/<id>', editarseriedisney, name='editarseriedisney'),
    path('recommendingtv/eliminarserienetflix/<id>', eliminarserienetflix, name='eliminarserienetflix'),
    path('recommendingtv/eliminarserieprime/<id>', eliminarserieprime, name='eliminarserieprime'),
    path('recommendingtv/eliminarseriehbo/<id>', eliminarseriehbo, name='eliminarseriehbo'),
    path('recommendingtv/eliminarseriedisney/<id>', eliminarseriedisney, name='eliminarseriedisney'),
    path('recommendingtv/busquedanetflix/', busquedanetflix, name='busquedanetflix'),
    path('recommendingtv/buscarserienetflix/', buscarserienetflix, name='buscarserienetflix'),
    path('recommendingtv/busquedaprime/', busquedaprime, name='busquedaprime'),
    path('recommendingtv/buscarserieprime/', buscarserieprime, name='buscarserieprime'),
    path('recommendingtv/busquedahbo/', busquedahbo, name='busquedahbo'),
    path('recommendingtv/buscarseriehbo/', buscarseriehbo, name='buscarseriehbo'),
    path('recommendingtv/busquedadisney/', busquedadisney, name='busquedadisney'),
    path('recommendingtv/buscarseriedisney/', buscarseriedisney, name='buscarseriedisney'),
    path('recommendingtv/registerapp/', registerapp, name='registerapp'),
    path('recommendingtv/loginapp/', loginapp, name='loginapp'),
    path('recommendingtv/logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('recommendingtv/perfil/', perfil, name='perfil'),
    path('recommendingtv/editarperfil/', editarperfil, name='editarperfil'),
]